[workspace]
resolver = "3"
members = [
    "baseline",
    "benchmark",
    "delta-encoded",
    "run-indexed",
    "unicode-id-trie-rle",
    "derived_core_properties",
    "unicode-id-start",
    "xid-visualization",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
